### ISSUE TITLE
Version 1.1.6 on npm breaks styling

### ISSUE THREAD

**Issue by AntonFriberg** [wmira/react-icons-kit#29]
The 1.1.6 version that is deployed on npm 8 days ago changes the behavior of the inline styling. I am also unable to override this styling with my own style prop. The change greatly affects the look of the icon since the div container takes up much more space.

With 1.1.6 I get the following styling
```css
div {
display: flex;
justify-content: center;
align-items: center;
}
```
Previously i got this.
```css
div {
display: inline-flex;
justify-content: center;
align-items: center;
}
```
Any reason why the 1.1.6 changes are not on github yet? Without the breaking changes published I am unable to provide pull request.
